:- multifile palavra/2.

palavra(animal, abelha).
palavra(animal, abutre).
palavra(animal, acana_preta).
palavra(animal, aguia).
palavra(animal, albatroz).
palavra(animal, alce).
palavra(animal, alpaca).
palavra(animal, anaconda).
palavra(animal, andorinha).
palavra(animal, anhuma).
palavra(animal, anta).
palavra(animal, antilope).
palavra(animal, aranha).
palavra(animal, arara).
palavra(animal, ararajuba).
palavra(animal, ariranha).
palavra(animal, asno).
palavra(animal, atum).
palavra(animal, avestruz).
palavra(animal, azulao).

palavra(animal, babuino).
palavra(animal, badejo).
palavra(animal, bagre).
palavra(animal, baiacu).
palavra(animal, baleia).
palavra(animal, barata).
palavra(animal, beija_flor).
palavra(animal, beluga).
palavra(animal, bem_te_vi).
palavra(animal, besouro).
palavra(animal, bicho_da_seda).
palavra(animal, bisao).
palavra(animal, bode).
palavra(animal, boi).
palavra(animal, borboleta).
palavra(animal, boto).
palavra(animal, bufalo).
palavra(animal, burro).

palavra(animal, cabra).
palavra(animal, cacatua).
palavra(animal, cachorro).
palavra(animal, calango).
palavra(animal, camaleao).
palavra(animal, camarao).
palavra(animal, camelo).
palavra(animal, camundongo).
palavra(animal, canario).
palavra(animal, canguru).
palavra(animal, capivara).
palavra(animal, caracol).
palavra(animal, caramujo).
palavra(animal, caranguejo).
palavra(animal, carneiro).
palavra(animal, carrapato).
palavra(animal, cavalo).
palavra(animal, cegonha).
palavra(animal, centopeia).
palavra(animal, chacal).
palavra(animal, cigarra).
palavra(animal, cisne).
palavra(animal, coala).
palavra(animal, cobra).
palavra(animal, codorna).
palavra(animal, coelho).
palavra(animal, coruja).
palavra(animal, crocodilo).
palavra(animal, cuica_lanosa).
palavra(animal, cupim).
palavra(animal, cutia).

palavra(animal, damao).
palavra(animal, diabo_da_tasmania).
palavra(animal, diamante_de_gould).
palavra(animal, dinossauro).
palavra(animal, doninha).
palavra(animal, dragao_de_komodo).
palavra(animal, dromedario).
palavra(animal, dugongo).

palavra(animal, elefante).
palavra(animal, ema).
palavra(animal, enguia).
palavra(animal, escorpiao).
palavra(animal, esponja).
palavra(animal, esquilo).
palavra(animal, estrela_do_mar).

palavra(animal, faisao).
palavra(animal, falcao).
palavra(animal, feneco).
palavra(animal, flamingo).
palavra(animal, foca).
palavra(animal, formiga).
palavra(animal, fuinha).
palavra(animal, furao).

palavra(animal, gafanhoto).
palavra(animal, gaivota).
palavra(animal, galo).
palavra(animal, gamba).
palavra(animal, gamo).
palavra(animal, ganso).
palavra(animal, garca).
palavra(animal, gato).
palavra(animal, gavial).
palavra(animal, gaviao).
palavra(animal, gazela).
palavra(animal, gecko_leopardo).
palavra(animal, girafa).
palavra(animal, gnu).
palavra(animal, golfinho).
palavra(animal, gorila).
palavra(animal, gralha).
palavra(animal, grilo).
palavra(animal, guanaco).
palavra(animal, guepardo).

palavra(animal, hadoque).
palavra(animal, hamster).
palavra(animal, harpia).
palavra(animal, hiena).
palavra(animal, hilochero).
palavra(animal, hipopotamo).

palavra(animal, ibex).
palavra(animal, iguana).
palavra(animal, impala).
palavra(animal, inhambu_chororo).
palavra(animal, irara).
palavra(animal, irauna).

palavra(animal, jabuti).
palavra(animal, jacana).
palavra(animal, jacare).
palavra(animal, jacutinga).
palavra(animal, jaguatirica).
palavra(animal, jamanta).
palavra(animal, jararaca).
palavra(animal, javali).
palavra(animal, jegue).
palavra(animal, jiboia).
palavra(animal, joaninha).
palavra(animal, jumento).

palavra(animal, kadavu_fantail).
palavra(animal, kakapo).
palavra(animal, kinguio).
palavra(animal, kiwi).
palavra(animal, kookaburra).
palavra(animal, kowari).
palavra(animal, krill).

palavra(animal, lacraia).
palavra(animal, lagarta).
palavra(animal, lagartixa).
palavra(animal, lagosta).
palavra(animal, lagostim).
palavra(animal, lambari).
palavra(animal, lampreia).
palavra(animal, leao).
palavra(animal, lebre).
palavra(animal, lemure).
palavra(animal, leopardo).
palavra(animal, lesma).
palavra(animal, lhama).
palavra(animal, libelula).
palavra(animal, lince).
palavra(animal, lobo).
palavra(animal, lombriga).
palavra(animal, lontra).
palavra(animal, louva_a_deus).
palavra(animal, lula).

palavra(animal, macaco).
palavra(animal, mamute).
palavra(animal, mangusto).
palavra(animal, marimbondo).
palavra(animal, mariposa).
palavra(animal, mariquita).
palavra(animal, maritaca).
palavra(animal, marmota).
palavra(animal, marreco).
palavra(animal, medusa).
palavra(animal, mico).
palavra(animal, minhoca).
palavra(animal, moco).
palavra(animal, morcego).
palavra(animal, moreia).
palavra(animal, morsa).
palavra(animal, mosca).
palavra(animal, mosquito).
palavra(animal, mula).

palavra(animal, nao_pode_parar).
palavra(animal, narval).
palavra(animal, negrinho_do_mato).
palavra(animal, neinei).
palavra(animal, nilgo).
palavra(animal, niquim).
palavra(animal, noitibo).
palavra(animal, noivinha).
palavra(animal, numbat).

palavra(animal, ocapi).
palavra(animal, ogea).
palavra(animal, onca).
palavra(animal, orangotango).
palavra(animal, orca).
palavra(animal, ornitorrinco).
palavra(animal, ostra).
palavra(animal, ourico).
palavra(animal, ourico_do_mar).
palavra(animal, ovelha).

palavra(animal, paca).
palavra(animal, pacupeba).
palavra(animal, panda).
palavra(animal, pangolim).
palavra(animal, pantera).
palavra(animal, papagaio).
palavra(animal, pardal).
palavra(animal, passaro).
palavra(animal, pato).
palavra(animal, pavao).
palavra(animal, peixe).
palavra(animal, peixe_boi_da_amazonia).
palavra(animal, pelicano).
palavra(animal, percevejo).
palavra(animal, perdiz).
palavra(animal, perereca).
palavra(animal, periquito).
palavra(animal, pernilongo).
palavra(animal, peru).
palavra(animal, pica_pau).
palavra(animal, pinguim).
palavra(animal, pintarroxo).
palavra(animal, pintassilgo).
palavra(animal, pinto).
palavra(animal, piolho).
palavra(animal, piranha).
palavra(animal, pirarucu).
palavra(animal, polvo).
palavra(animal, pombo).
palavra(animal, ponei).
palavra(animal, porco).
palavra(animal, porco_espinho).
palavra(animal, porquinho_da_india).
palavra(animal, prea).
palavra(animal, preguica).
palavra(animal, pulga).
palavra(animal, puma).

palavra(animal, quati).
palavra(animal, quebra_nozes).
palavra(animal, quero_quero).
palavra(animal, quetzal).
palavra(animal, quimera).
palavra(animal, quem_te_vestiu).
palavra(animal, quete_do_sul).

palavra(animal, sabia).
palavra(animal, sagui).
palavra(animal, salamandra).
palavra(animal, salmao).
palavra(animal, sanguessuga).
palavra(animal, sapo).
palavra(animal, sardinha).
palavra(animal, sarue).
palavra(animal, seriema).
palavra(animal, serpente).
palavra(animal, serval).
palavra(animal, siri).
palavra(animal, sucuarana).
palavra(animal, sucuri).
palavra(animal, suricate).
palavra(animal, surubim).

palavra(animal, tainha).
palavra(animal, tamandua).
palavra(animal, tamboril).
palavra(animal, tangara).
palavra(animal, tartaruga).
palavra(animal, tatu).
palavra(animal, tatui).
palavra(animal, teiu).
palavra(animal, texugo).
palavra(animal, teredo).
palavra(animal, tigre).
palavra(animal, tilapia).
palavra(animal, toupeira).
palavra(animal, touro).
palavra(animal, traca).
palavra(animal, tritao).
palavra(animal, truta).
palavra(animal, tubarao).
palavra(animal, tucano).
palavra(animal, tucunare).
palavra(animal, tucuxi).
palavra(animal, tuiuiu).
palavra(animal, tupaia).

palavra(animal, unicornio).
palavra(animal, urso).
palavra(animal, urubu).
palavra(animal, urumutum).
palavra(animal, uirapuru_de_peito_branco).
palavra(animal, ui_pi).
palavra(animal, uirapuruzinho).

palavra(animal, vaca).
palavra(animal, vaga_lume).
palavra(animal, veado).
palavra(animal, verdilhao).
palavra(animal, vespa).
palavra(animal, vibora).
palavra(animal, vombate).
palavra(animal, vicunha).
palavra(animal, vieira).
palavra(animal, vison).

palavra(animal, carrica_do_chaparral).
palavra(animal, wallaby).

palavra(animal, xaia).
palavra(animal, xexeu).
palavra(animal, ximango).
palavra(animal, xue).
palavra(animal, xuri).

palavra(animal, cagarro_levantino).
palavra(animal, inambu).

palavra(animal, zebra).
palavra(animal, zebu).
palavra(animal, zangao).
palavra(animal, zorrilho).
palavra(animal, zaglosso).
palavra(animal, zabele).
palavra(animal, zaragateiro).
palavra(animal, zogue_zogue).