:- module(animais, [word/2]). 
%:- module(`nome do modulo`, `[predicado/nº de argumentos]`).

word(animal, abelha).
word(animal, abutre).
word(animal, acana_preta).
word(animal, aguia).
word(animal, albatroz).
word(animal, alce).
word(animal, alpaca).
word(animal, anaconda).
word(animal, andorinha).
word(animal, anhuma).
word(animal, anta).
word(animal, antilope).
word(animal, aranha).
word(animal, arara).
word(animal, ararajuba).
word(animal, ariranha).
word(animal, asno).
word(animal, atum).
word(animal, avestruz).
word(animal, azulao).

word(animal, babuino).
word(animal, badejo).
word(animal, bagre).
word(animal, baiacu).
word(animal, baleia).
word(animal, barata).
word(animal, beija_flor).
word(animal, beluga).
word(animal, bem_te_vi).
word(animal, besouro).
word(animal, bicho_da_seda).
word(animal, bisao).
word(animal, bode).
word(animal, boi).
word(animal, borboleta).
word(animal, boto).
word(animal, bufalo).
word(animal, burro).

word(animal, cabra).
word(animal, cacatua).
word(animal, cachorro).
word(animal, calango).
word(animal, camaleao).
word(animal, camarao).
word(animal, camelo).
word(animal, camundongo).
word(animal, canario).
word(animal, canguru).
word(animal, capivara).
word(animal, caracol).
word(animal, caramujo).
word(animal, caranguejo).
word(animal, carneiro).
word(animal, carrapato).
word(animal, cavalo).
word(animal, cegonha).
word(animal, centopeia).
word(animal, chacal).
word(animal, cigarra).
word(animal, cisne).
word(animal, coala).
word(animal, cobra).
word(animal, codorna).
word(animal, coelho).
word(animal, coruja).
word(animal, crocodilo).
word(animal, cuica_lanosa).
word(animal, cupim).
word(animal, cutia).

word(animal, damao).
word(animal, diabo_da_tasmania).
word(animal, diamante_de_gould).
word(animal, dinossauro).
word(animal, doninha).
word(animal, dragao_de_komodo).
word(animal, dromedario).
word(animal, dugongo).

word(animal, elefante).
word(animal, ema).
word(animal, enguia).
word(animal, escorpiao).
word(animal, esponja).
word(animal, esquilo).
word(animal, estrela_do_mar).

word(animal, faisao).
word(animal, falcao).
word(animal, feneco).
word(animal, flamingo).
word(animal, foca).
word(animal, formiga).
word(animal, fuinha).
word(animal, furao).

word(animal, gafanhoto).
word(animal, gaivota).
word(animal, galo).
word(animal, gamba).
word(animal, gamo).
word(animal, ganso).
word(animal, garca).
word(animal, gato).
word(animal, gavial).
word(animal, gaviao).
word(animal, gazela).
word(animal, gecko_leopardo).
word(animal, girafa).
word(animal, gnu).
word(animal, golfinho).
word(animal, gorila).
word(animal, gralha).
word(animal, grilo).
word(animal, guanaco).
word(animal, guepardo).

word(animal, hadoque).
word(animal, hamster).
word(animal, harpia).
word(animal, hiena).
word(animal, hilochero).
word(animal, hipopotamo).

word(animal, ibex).
word(animal, iguana).
word(animal, impala).
word(animal, inhambu_chororo).
word(animal, irara).
word(animal, irauna).

word(animal, jabuti).
word(animal, jacana).
word(animal, jacare).
word(animal, jacutinga).
word(animal, jaguatirica).
word(animal, jamanta).
word(animal, jararaca).
word(animal, javali).
word(animal, jegue).
word(animal, jiboia).
word(animal, joaninha).
word(animal, jumento).

word(animal, kadavu_fantail).
word(animal, kakapo).
word(animal, kinguio).
word(animal, kiwi).
word(animal, kookaburra).
word(animal, kowari).
word(animal, krill).

word(animal, lacraia).
word(animal, lagarta).
word(animal, lagartixa).
word(animal, lagosta).
word(animal, lagostim).
word(animal, lambari).
word(animal, lampreia).
word(animal, leao).
word(animal, lebre).
word(animal, lemure).
word(animal, leopardo).
word(animal, lesma).
word(animal, lhama).
word(animal, libelula).
word(animal, lince).
word(animal, lobo).
word(animal, lombriga).
word(animal, lontra).
word(animal, louva_a_deus).
word(animal, lula).

word(animal, macaco).
word(animal, mamute).
word(animal, mangusto).
word(animal, marimbondo).
word(animal, mariposa).
word(animal, mariquita).
word(animal, maritaca).
word(animal, marmota).
word(animal, marreco).
word(animal, medusa).
word(animal, mico).
word(animal, minhoca).
word(animal, moco).
word(animal, morcego).
word(animal, moreia).
word(animal, morsa).
word(animal, mosca).
word(animal, mosquito).
word(animal, mula).

word(animal, nao_pode_parar).
word(animal, narval).
word(animal, negrinho_do_mato).
word(animal, neinei).
word(animal, nilgo).
word(animal, niquim).
word(animal, noitibo).
word(animal, noivinha).
word(animal, numbat).

word(animal, ocapi).
word(animal, ogea).
word(animal, onca).
word(animal, orangotango).
word(animal, orca).
word(animal, ornitorrinco).
word(animal, ostra).
word(animal, ourico).
word(animal, ourico_do_mar).
word(animal, ovelha).

word(animal, paca).
word(animal, pacupeba).
word(animal, panda).
word(animal, pangolim).
word(animal, pantera).
word(animal, papagaio).
word(animal, pardal).
word(animal, passaro).
word(animal, pato).
word(animal, pavao).
word(animal, peixe).
word(animal, peixe_boi_da_amazonia).
word(animal, pelicano).
word(animal, percevejo).
word(animal, perdiz).
word(animal, perereca).
word(animal, periquito).
word(animal, pernilongo).
word(animal, peru).
word(animal, pica_pau).
word(animal, pinguim).
word(animal, pintarroxo).
word(animal, pintassilgo).
word(animal, pinto).
word(animal, piolho).
word(animal, piranha).
word(animal, pirarucu).
word(animal, polvo).
word(animal, pombo).
word(animal, ponei).
word(animal, porco).
word(animal, porco_espinho).
word(animal, porquinho_da_india).
word(animal, prea).
word(animal, preguica).
word(animal, pulga).
word(animal, puma).

word(animal, quati).
word(animal, quebra_nozes).
word(animal, quero_quero).
word(animal, quetzal).
word(animal, quimera).
word(animal, quem_te_vestiu).
word(animal, quete_do_sul).

word(animal, sabia).
word(animal, sagui).
word(animal, salamandra).
word(animal, salmao).
word(animal, sanguessuga).
word(animal, sapo).
word(animal, sardinha).
word(animal, sarue).
word(animal, seriema).
word(animal, serpente).
word(animal, serval).
word(animal, siri).
word(animal, sucuarana).
word(animal, sucuri).
word(animal, suricate).
word(animal, surubim).

word(animal, tainha).
word(animal, tamandua).
word(animal, tamboril).
word(animal, tangara).
word(animal, tartaruga).
word(animal, tatu).
word(animal, tatui).
word(animal, teiu).
word(animal, texugo).
word(animal, teredo).
word(animal, tigre).
word(animal, tilapia).
word(animal, toupeira).
word(animal, touro).
word(animal, traca).
word(animal, tritao).
word(animal, truta).
word(animal, tubarao).
word(animal, tucano).
word(animal, tucunare).
word(animal, tucuxi).
word(animal, tuiuiu).
word(animal, tupaia).

word(animal, unicornio).
word(animal, urso).
word(animal, urubu).
word(animal, urumutum).
word(animal, uirapuru_de_peito_branco).
word(animal, ui_pi).
word(animal, uirapuruzinho).

word(animal, vaca).
word(animal, vaga_lume).
word(animal, veado).
word(animal, verdilhao).
word(animal, vespa).
word(animal, vibora).
word(animal, vombate).
word(animal, vicunha).
word(animal, vieira).
word(animal, vison).

word(animal, carrica_do_chaparral).
word(animal, wallaby).

word(animal, xaia).
word(animal, xexeu).
word(animal, ximango).
word(animal, xue).
word(animal, xuri).

word(animal, cagarro_levantino).
word(animal, inambu).

word(animal, zebra).
word(animal, zebu).
word(animal, zangao).
word(animal, zorrilho).
word(animal, zaglosso).
word(animal, zabele).
word(animal, zaragateiro).
word(animal, zogue_zogue).
