:- module(animais, [word/2]). 
%:- module(`nome do modulo`, `[predicado/nº de argumentos]`).

word(animal, cachorro).
word(animal, gato).
word(animal, lobo).
word(animal, raposa).
word(animal, leao).
word(animal, tigre).
word(animal, onca).
word(animal, guepardo).
word(animal, elefante).
word(animal, rinoceronte).
word(animal, hipopotamo).
word(animal, girafa).
word(animal, zebra).
word(animal, cavalo).
word(animal, burro).
word(animal, camelo).
word(animal, alpaca).
word(animal, lhama).
word(animal, coelho).
word(animal, esquilo).
word(animal, castor).
word(animal, hamster).
word(animal, rato).
word(animal, morcego).
word(animal, macaco).
word(animal, gorila).
word(animal, chimpanze).
word(animal, orangotango).
word(animal, panda).
word(animal, koala).
word(animal, canguru).
word(animal, pinguim).
word(animal, avestruz).
word(animal, aguia).
word(animal, falcao).
word(animal, coruja).
word(animal, papagaio).
word(animal, tucano).
word(animal, flamingo).
word(animal, crocodilo).
word(animal, jacare).
word(animal, tartaruga).
word(animal, iguana).
word(animal, cobra).
word(animal, tubarao).
word(animal, baleia).
word(animal, golfinho).
word(animal, polvo).
word(animal, lula).
word(animal, caranguejo).