:- module(frutas, [word/2]).

word(fruta, abacate).
word(fruta, abacaxi).
word(fruta, abiu).
word(fruta, abrico).
word(fruta, abrunho).
word(fruta, acai).
word(fruta, acerola).
word(fruta, akee).
word(fruta, alfarroba).
word(fruta, ameixa).
word(fruta, amendoa).
word(fruta, amora).
word(fruta, ananas).
word(fruta, anona).
word(fruta, araca).
word(fruta, arando).
word(fruta, araticum).
word(fruta, arbuto).
word(fruta, aroeira).
word(fruta, ata).
word(fruta, atemoia).
word(fruta, avela).
word(fruta, avenca).
word(fruta, babaco).
word(fruta, babacu).
word(fruta, bacaba).
word(fruta, bacupari).
word(fruta, bacuri).
word(fruta, banana).
word(fruta, baoba).
word(fruta, barbatimao).
word(fruta, beldroega).
word(fruta, bergamota).
word(fruta, biriba).
word(fruta, borojo).
word(fruta, buriti).
word(fruta, butia).
word(fruta, cacau).
word(fruta, cacto).
word(fruta, caja).
word(fruta, caja_manga).
word(fruta, caju).
word(fruta, calabura).
word(fruta, calamondin).
word(fruta, camapu).
word(fruta, cambuci).
word(fruta, cambui).
word(fruta, camu_camu).
word(fruta, cana_de_acucar).
word(fruta, canistel).
word(fruta, caqui).
word(fruta, carambola).
word(fruta, carandai).
word(fruta, cardo).
word(fruta, carnauba).
word(fruta, caroa).
word(fruta, carqueja).
word(fruta, castanha).
word(fruta, catole).
word(fruta, cereja).
word(fruta, chalota).
word(fruta, chicoria).
word(fruta, chuchu).
word(fruta, cidra).
word(fruta, coco).
word(fruta, coquinho_azedo).
word(fruta, coracao_de_boi).
word(fruta, corniso).
word(fruta, cranberry).
word(fruta, cucumis).
word(fruta, cupuacu).
word(fruta, currants).
word(fruta, dactilo).
word(fruta, damasco).
word(fruta, dekopon).
word(fruta, dende).
word(fruta, dendezeiro).
word(fruta, diospiro).
word(fruta, dovyalis).
word(fruta, duriao).
word(fruta, eburuna).
word(fruta, embaibarana).
word(fruta, embauba).
word(fruta, embaubarana).
word(fruta, endro).
word(fruta, engkala).
word(fruta, erva_cidreira).
word(fruta, erva_doce).
word(fruta, erva_mate).
word(fruta, escarola).
word(fruta, escropari).
word(fruta, esfregadinha).
word(fruta, espinafre).
word(fruta, eugenia).
word(fruta, falsa_oliveira).
word(fruta, farinha_seca).
word(fruta, feijao).
word(fruta, feijoa).
word(fruta, ficoide).
word(fruta, figo).
word(fruta, figo_da_india).
word(fruta, framboesa).
word(fruta, fruta_de_cedro).
word(fruta, fruta_de_lobo).
word(fruta, fruta_de_tatu).
word(fruta, fruta_do_conde).
word(fruta, fruta_pao).
word(fruta, frutao).
word(fruta, gabiroba).
word(fruta, goiaba).
word(fruta, goiaba_serrana).
word(fruta, goji_berry).
word(fruta, goldenberry).
word(fruta, granada).
word(fruta, granadilla).
word(fruta, gravata).
word(fruta, graviola).
word(fruta, groselha).
word(fruta, grumixama).
word(fruta, guabiju).
word(fruta, guarana).
word(fruta, hala).
word(fruta, haritaki).
word(fruta, hawthorn).
word(fruta, heisteria).
word(fruta, hilocereo).
word(fruta, horned_melon).
word(fruta, huito).
word(fruta, ibacurupari).
word(fruta, ibatingui).
word(fruta, icaco).
word(fruta, ilama).
word(fruta, imbu).
word(fruta, inaja).
word(fruta, inga).
word(fruta, inhame).
word(fruta, itauba).
word(fruta, jaba).
word(fruta, jabuticaba).
word(fruta, jaca).
word(fruta, jacaratia).
word(fruta, jalapa).
word(fruta, jambo).
word(fruta, jambo_vermelho).
word(fruta, jambolao).
word(fruta, jambu).
word(fruta, jaracatia).
word(fruta, jatoba).
word(fruta, jenipapo).
word(fruta, jeriva).
word(fruta, jua).
word(fruta, jujuba).
word(fruta, junca).
word(fruta, kabosu).
word(fruta, kaki).
word(fruta, kawakawa).
word(fruta, kinkan).
word(fruta, kino).
word(fruta, kiwano).
word(fruta, kiwi).
word(fruta, kumquat).
word(fruta, laranja).
word(fruta, laranja_baia).
word(fruta, laranja_kinkan).
word(fruta, laranja_lima).
word(fruta, laranjinha).
word(fruta, lichia).
word(fruta, lima).
word(fruta, lima_da_persia).
word(fruta, limao).
word(fruta, limao_cravo).
word(fruta, limao_siciliano).
word(fruta, lobeira).
word(fruta, longan).
word(fruta, lucuma).
word(fruta, maca).
word(fruta, maca_do_amor).
word(fruta, maca_verde).
word(fruta, macadamia).
word(fruta, macauba).
word(fruta, malagueta).
word(fruta, mamao).
word(fruta, mamao_papaia).
word(fruta, mamica_de_cadela).
word(fruta, mamoncillo).
word(fruta, mana_cubiu).
word(fruta, manga).
word(fruta, mangaba).
word(fruta, mangostao).
word(fruta, maracuja).
word(fruta, maracuja_acu).
word(fruta, maracuja_do_cerrado).
word(fruta, marang).
word(fruta, marmelo).
word(fruta, marolo).
word(fruta, massaranduba).
word(fruta, melancia).
word(fruta, melancia_pequena).
word(fruta, melao).
word(fruta, melao_andino).
word(fruta, melao_de_sao_caetano).
word(fruta, mirtilo).
word(fruta, mombuca).
word(fruta, monstera).
word(fruta, morango).
word(fruta, morango_silvestre).
word(fruta, murici).
word(fruta, mussambe).
word(fruta, naranjilla).
word(fruta, nectarina).
word(fruta, nescafe).
word(fruta, nespera).
word(fruta, niguebito).
word(fruta, noni).
word(fruta, noz).
word(fruta, noz_moscada).
word(fruta, oiti).
word(fruta, olho_de_boi).
word(fruta, olho_de_dragao).
word(fruta, oliva).
word(fruta, oliveira).
word(fruta, ora_pro_nobis).
word(fruta, orangelo).
word(fruta, ouricuri).
word(fruta, oxicoco).
word(fruta, pera).
word(fruta, pessego).
word(fruta, physalis).
word(fruta, pindaiba).
word(fruta, pinha).
word(fruta, pinhao).
word(fruta, piqui).
word(fruta, piranga).
word(fruta, pistache).
word(fruta, pitanga).
word(fruta, pitaya).
word(fruta, pitomba).
word(fruta, pomelo).
word(fruta, ponei).
word(fruta, quina).
word(fruta, quince).
word(fruta, rambai).
word(fruta, rambutao).
word(fruta, raspberry).
word(fruta, roma).
word(fruta, rukam).
word(fruta, salak).
word(fruta, sapota).
word(fruta, sapoti).
word(fruta, sapucaia).
word(fruta, seriguela).
word(fruta, tamara).
word(fruta, tamarindo).
word(fruta, tangerina).
word(fruta, toranja).
word(fruta, tucuma).
word(fruta, umbu).
word(fruta, ume).
word(fruta, uva).
word(fruta, uvaia).
word(fruta, uxi).
word(fruta, vacinio).
word(fruta, vangueria).
word(fruta, veludo).
word(fruta, vergamota).
word(fruta, wampi).
word(fruta, watermelon).
word(fruta, wolfberry).
word(fruta, ximenia).
word(fruta, xixa).
word(fruta, xixa_do_cerrado).
word(fruta, yamamomo).
word(fruta, yangmei).
word(fruta, yuzu).
word(fruta, zimbro).
word(fruta, zizyphus).
word(fruta, avela).
word(fruta, lichia).
word(fruta, physalis).
