:- multifile palavra/2.

palavra(fruta, abacate).
palavra(fruta, abacaxi).
palavra(fruta, abiu).
palavra(fruta, abrico).
palavra(fruta, abrunho).
palavra(fruta, acai).
palavra(fruta, acerola).
palavra(fruta, akee).
palavra(fruta, alfarroba).
palavra(fruta, ameixa).
palavra(fruta, amendoa).
palavra(fruta, amora).
palavra(fruta, ananas).
palavra(fruta, anona).
palavra(fruta, araca).
palavra(fruta, arando).
palavra(fruta, araticum).
palavra(fruta, arbuto).
palavra(fruta, aroeira).
palavra(fruta, ata).
palavra(fruta, atemoia).
palavra(fruta, avela).
palavra(fruta, avenca).
palavra(fruta, babaco).
palavra(fruta, babacu).
palavra(fruta, bacaba).
palavra(fruta, bacupari).
palavra(fruta, bacuri).
palavra(fruta, banana).
palavra(fruta, baoba).
palavra(fruta, barbatimao).
palavra(fruta, beldroega).
palavra(fruta, bergamota).
palavra(fruta, biriba).
palavra(fruta, borojo).
palavra(fruta, buriti).
palavra(fruta, butia).
palavra(fruta, cacau).
palavra(fruta, cacto).
palavra(fruta, caja).
palavra(fruta, caja_manga).
palavra(fruta, caju).
palavra(fruta, calabura).
palavra(fruta, calamondin).
palavra(fruta, camapu).
palavra(fruta, cambuci).
palavra(fruta, cambui).
palavra(fruta, camu_camu).
palavra(fruta, cana_de_acucar).
palavra(fruta, canistel).
palavra(fruta, caqui).
palavra(fruta, carambola).
palavra(fruta, carandai).
palavra(fruta, cardo).
palavra(fruta, carnauba).
palavra(fruta, caroa).
palavra(fruta, carqueja).
palavra(fruta, castanha).
palavra(fruta, catole).
palavra(fruta, cereja).
palavra(fruta, chalota).
palavra(fruta, chicoria).
palavra(fruta, chuchu).
palavra(fruta, cidra).
palavra(fruta, coco).
palavra(fruta, coquinho_azedo).
palavra(fruta, coracao_de_boi).
palavra(fruta, corniso).
palavra(fruta, cranberry).
palavra(fruta, cucumis).
palavra(fruta, cupuacu).
palavra(fruta, currants).
palavra(fruta, dactilo).
palavra(fruta, damasco).
palavra(fruta, dekopon).
palavra(fruta, dende).
palavra(fruta, dendezeiro).
palavra(fruta, diospiro).
palavra(fruta, dovyalis).
palavra(fruta, duriao).
palavra(fruta, eburuna).
palavra(fruta, embaibarana).
palavra(fruta, embauba).
palavra(fruta, embaubarana).
palavra(fruta, endro).
palavra(fruta, engkala).
palavra(fruta, erva_cidreira).
palavra(fruta, erva_doce).
palavra(fruta, erva_mate).
palavra(fruta, escarola).
palavra(fruta, escropari).
palavra(fruta, esfregadinha).
palavra(fruta, espinafre).
palavra(fruta, eugenia).
palavra(fruta, falsa_oliveira).
palavra(fruta, farinha_seca).
palavra(fruta, feijao).
palavra(fruta, feijoa).
palavra(fruta, ficoide).
palavra(fruta, figo).
palavra(fruta, figo_da_india).
palavra(fruta, framboesa).
palavra(fruta, fruta_de_cedro).
palavra(fruta, fruta_de_lobo).
palavra(fruta, fruta_de_tatu).
palavra(fruta, fruta_do_conde).
palavra(fruta, fruta_pao).
palavra(fruta, frutao).
palavra(fruta, gabiroba).
palavra(fruta, goiaba).
palavra(fruta, goiaba_serrana).
palavra(fruta, goji_berry).
palavra(fruta, goldenberry).
palavra(fruta, granada).
palavra(fruta, granadilla).
palavra(fruta, gravata).
palavra(fruta, graviola).
palavra(fruta, groselha).
palavra(fruta, grumixama).
palavra(fruta, guabiju).
palavra(fruta, guarana).
palavra(fruta, hala).
palavra(fruta, haritaki).
palavra(fruta, hawthorn).
palavra(fruta, heisteria).
palavra(fruta, hilocereo).
palavra(fruta, horned_melon).
palavra(fruta, huito).
palavra(fruta, ibacurupari).
palavra(fruta, ibatingui).
palavra(fruta, icaco).
palavra(fruta, ilama).
palavra(fruta, imbu).
palavra(fruta, inaja).
palavra(fruta, inga).
palavra(fruta, inhame).
palavra(fruta, itauba).
palavra(fruta, jaba).
palavra(fruta, jabuticaba).
palavra(fruta, jaca).
palavra(fruta, jacaratia).
palavra(fruta, jalapa).
palavra(fruta, jambo).
palavra(fruta, jambo_vermelho).
palavra(fruta, jambolao).
palavra(fruta, jambu).
palavra(fruta, jaracatia).
palavra(fruta, jatoba).
palavra(fruta, jenipapo).
palavra(fruta, jeriva).
palavra(fruta, jua).
palavra(fruta, jujuba).
palavra(fruta, junca).
palavra(fruta, kabosu).
palavra(fruta, kaki).
palavra(fruta, kawakawa).
palavra(fruta, kinkan).
palavra(fruta, kino).
palavra(fruta, kiwano).
palavra(fruta, kiwi).
palavra(fruta, kumquat).
palavra(fruta, laranja).
palavra(fruta, laranja_baia).
palavra(fruta, laranja_kinkan).
palavra(fruta, laranja_lima).
palavra(fruta, laranjinha).
palavra(fruta, lichia).
palavra(fruta, lima).
palavra(fruta, lima_da_persia).
palavra(fruta, limao).
palavra(fruta, limao_cravo).
palavra(fruta, limao_siciliano).
palavra(fruta, lobeira).
palavra(fruta, longan).
palavra(fruta, lucuma).
palavra(fruta, maca).
palavra(fruta, maca_do_amor).
palavra(fruta, maca_verde).
palavra(fruta, macadamia).
palavra(fruta, macauba).
palavra(fruta, malagueta).
palavra(fruta, mamao).
palavra(fruta, mamao_papaia).
palavra(fruta, mamica_de_cadela).
palavra(fruta, mamoncillo).
palavra(fruta, mana_cubiu).
palavra(fruta, manga).
palavra(fruta, mangaba).
palavra(fruta, mangostao).
palavra(fruta, maracuja).
palavra(fruta, maracuja_acu).
palavra(fruta, maracuja_do_cerrado).
palavra(fruta, marang).
palavra(fruta, marmelo).
palavra(fruta, marolo).
palavra(fruta, massaranduba).
palavra(fruta, melancia).
palavra(fruta, melancia_pequena).
palavra(fruta, melao).
palavra(fruta, melao_andino).
palavra(fruta, melao_de_sao_caetano).
palavra(fruta, mirtilo).
palavra(fruta, mombuca).
palavra(fruta, monstera).
palavra(fruta, morango).
palavra(fruta, morango_silvestre).
palavra(fruta, murici).
palavra(fruta, mussambe).
palavra(fruta, naranjilla).
palavra(fruta, nectarina).
palavra(fruta, nescafe).
palavra(fruta, nespera).
palavra(fruta, niguebito).
palavra(fruta, noni).
palavra(fruta, noz).
palavra(fruta, noz_moscada).
palavra(fruta, oiti).
palavra(fruta, olho_de_boi).
palavra(fruta, olho_de_dragao).
palavra(fruta, oliva).
palavra(fruta, oliveira).
palavra(fruta, ora_pro_nobis).
palavra(fruta, orangelo).
palavra(fruta, ouricuri).
palavra(fruta, oxicoco).
palavra(fruta, pera).
palavra(fruta, pessego).
palavra(fruta, physalis).
palavra(fruta, pindaiba).
palavra(fruta, pinha).
palavra(fruta, pinhao).
palavra(fruta, piqui).
palavra(fruta, piranga).
palavra(fruta, pistache).
palavra(fruta, pitanga).
palavra(fruta, pitaya).
palavra(fruta, pitomba).
palavra(fruta, pomelo).
palavra(fruta, ponei).
palavra(fruta, quina).
palavra(fruta, quince).
palavra(fruta, rambai).
palavra(fruta, rambutao).
palavra(fruta, raspberry).
palavra(fruta, roma).
palavra(fruta, rukam).
palavra(fruta, salak).
palavra(fruta, sapota).
palavra(fruta, sapoti).
palavra(fruta, sapucaia).
palavra(fruta, seriguela).
palavra(fruta, tamara).
palavra(fruta, tamarindo).
palavra(fruta, tangerina).
palavra(fruta, toranja).
palavra(fruta, tucuma).
palavra(fruta, umbu).
palavra(fruta, ume).
palavra(fruta, uva).
palavra(fruta, uvaia).
palavra(fruta, uxi).
palavra(fruta, vacinio).
palavra(fruta, vangueria).
palavra(fruta, veludo).
palavra(fruta, vergamota).
palavra(fruta, wampi).
palavra(fruta, watermelon).
palavra(fruta, wolfberry).
palavra(fruta, ximenia).
palavra(fruta, xixa).
palavra(fruta, xixa_do_cerrado).
palavra(fruta, yamamomo).
palavra(fruta, yangmei).
palavra(fruta, yuzu).
palavra(fruta, zimbro).
palavra(fruta, zizyphus).
palavra(fruta, avela).
palavra(fruta, lichia).
palavra(fruta, physalis).