:- module(frutas, [word/2]).

word(fruta, abacaxi).
word(fruta, abacate).
word(fruta, acerola).
word(fruta, ameixa).
word(fruta, amora).
word(fruta, banana).
word(fruta, caju).
word(fruta, caqui).
word(fruta, carambola).
word(fruta, cereja).
word(fruta, coco).
word(fruta, figo).
word(fruta, framboesa).
word(fruta, goiaba).
word(fruta, graviola).
word(fruta, jabuticaba).
word(fruta, jaca).
word(fruta, kiwi).
word(fruta, laranja).
word(fruta, lima).
word(fruta, limao).
word(fruta, maca).
word(fruta, mamao).
word(fruta, manga).
word(fruta, maracuja).
word(fruta, melancia).
word(fruta, melao).
word(fruta, morango).
word(fruta, nectarina).
word(fruta, pera).
word(fruta, pessego).
word(fruta, pitanga).
word(fruta, roma).
word(fruta, tamarindo).
word(fruta, tangerina).
word(fruta, uva).
word(fruta, cupuacu).
word(fruta, avela).
word(fruta, lichia).
word(fruta, physalis).