:- module(paises, [word/2]).

word(pais, afeganistao).
word(pais, africa_do_sul).
word(pais, albania).
word(pais, alemanha).
word(pais, andorra).
word(pais, angola).
word(pais, antiga_e_barbuda).
word(pais, arabia_saudita).
word(pais, argelia).
word(pais, argentina).
word(pais, armenia).
word(pais, australia).
word(pais, austria).
word(pais, azerbaijao).
word(pais, bahamas).
word(pais, bahrein).
word(pais, bangladesh).
word(pais, barbados).
word(pais, belarus).
word(pais, belgica).
word(pais, belize).
word(pais, benin).
word(pais, butao).
word(pais, bolivia).
word(pais, bosnia_e_herzegovina).
word(pais, botsuana).
word(pais, brasil).
word(pais, brunei).
word(pais, bulgaria).
word(pais, burkina_faso).
word(pais, burundi).
word(pais, cabo_verde).
word(pais, camboja).
word(pais, camaroes).
word(pais, canada).
word(pais, catar).
word(pais, cazaquistao).
word(pais, chade).
word(pais, chile).
word(pais, china).
word(pais, chipre).
word(pais, colombia).
word(pais, comores).
word(pais, congo).
word(pais, coreia_do_norte).
word(pais, coreia_do_sul).
word(pais, costa_do_marfim).
word(pais, costa_rica).
word(pais, croacia).
word(pais, cuba).
word(pais, dinamarca).
word(pais, djibuti).
word(pais, dominica).
word(pais, egito).
word(pais, el_salvador).
word(pais, emirados_arabes_unidos).
word(pais, equador).
word(pais, eritreia).
word(pais, eslovaquia).
word(pais, eslovenia).
word(pais, espanha).
word(pais, estados_unidos).
word(pais, estonia).
word(pais, eswatini).
word(pais, etiopia).
word(pais, fiji).
word(pais, filipinas).
word(pais, finlandia).
word(pais, franca).
word(pais, gabao).
word(pais, gambia).
word(pais, gana).
word(pais, georgia).
word(pais, granada).
word(pais, grecia).
word(pais, guatemala).
word(pais, guiana).
word(pais, guine).
word(pais, guine_bissau).
word(pais, guine_equatorial).
word(pais, haiti).
word(pais, honduras).
word(pais, hungria).
word(pais, iemen).
word(pais, ilhas_marshall).
word(pais, india).
word(pais, indonesia).
word(pais, ira).
word(pais, iraque).
word(pais, irlanda).
word(pais, islandia).
word(pais, israel).
word(pais, italia).
word(pais, jamaica).
word(pais, japao).
word(pais, jordania).
word(pais, kiribati).
word(pais, kuwait).
word(pais, laos).
word(pais, lesoto).
word(pais, letonia).
word(pais, libano).
word(pais, liberia).
word(pais, libia).
word(pais, liechtenstein).
word(pais, lituania).
word(pais, luxemburgo).
word(pais, macedonia_do_norte).
word(pais, madagascar).
word(pais, malasia).
word(pais, malawi).
word(pais, maldivas).
word(pais, mali).
word(pais, malta).
word(pais, marrocos).
word(pais, mauricio).
word(pais, mauritania).
word(pais, mexico).
word(pais, micronesia).
word(pais, mocambique).
word(pais, moldavia).
word(pais, monaco).
word(pais, mongolia).
word(pais, montenegro).
word(pais, myanmar).
word(pais, namibia).
word(pais, nauru).
word(pais, nepal).
word(pais, nicaragua).
word(pais, niger).
word(pais, nigeria).
word(pais, noruega).
word(pais, nova_zelandia).
word(pais, oma).
word(pais, paises_baixos).
word(pais, palau).
word(pais, panama).
word(pais, papua_nova_guine).
word(pais, paquistao).
word(pais, paraguai).
word(pais, peru).
word(pais, polonia).
word(pais, portugal).
word(pais, quenia).
word(pais, quirguistao).
word(pais, reino_unido).
word(pais, republica_centro_africana).
word(pais, republica_democratica_do_congo).
word(pais, republica_dominicana).
word(pais, republica_tcheca).
word(pais, romenia).
word(pais, ruanda).
word(pais, russia).
word(pais, samoa).
word(pais, sao_cristovao_e_neves).
word(pais, sao_marinho).
word(pais, sao_tome_e_principe).
word(pais, sao_vicente_e_granadinas).
word(pais, seicheles).
word(pais, senegal).
word(pais, serra_leoa).
word(pais, servia).
word(pais, singapura).
word(pais, siria).
word(pais, somalia).
word(pais, sri_lanka).
word(pais, sudao).
word(pais, sudao_do_sul).
word(pais, suecia).
word(pais, suica).
word(pais, suriname).
word(pais, tailandia).
word(pais, tajiquistao).
word(pais, tanzania).
word(pais, timor_leste).
word(pais, togo).
word(pais, tonga).
word(pais, trinidad_e_tobago).
word(pais, tunisia).
word(pais, turcomenistao).
word(pais, turquia).
word(pais, tuvalu).
word(pais, ucrania).
word(pais, uganda).
word(pais, uruguai).
word(pais, uzbequistao).
word(pais, vanuatu).
word(pais, venezuela).
word(pais, vietna).
word(pais, zambia).
word(pais, zimbabue).