:- multifile palavra/2. % Permite que as cláusulas de um mesmo predicado sejam definidas em diversos arquivos de origem

palavra(pais, afeganistao).
palavra(pais, africa_do_sul).
palavra(pais, albania).
palavra(pais, alemanha).
palavra(pais, andorra).
palavra(pais, angola).
palavra(pais, antiga_e_barbuda).
palavra(pais, arabia_saudita).
palavra(pais, argelia).
palavra(pais, argentina).
palavra(pais, armenia).
palavra(pais, australia).
palavra(pais, austria).
palavra(pais, azerbaijao).
palavra(pais, bahamas).
palavra(pais, bahrein).
palavra(pais, bangladesh).
palavra(pais, barbados).
palavra(pais, belarus).
palavra(pais, belgica).
palavra(pais, belize).
palavra(pais, benin).
palavra(pais, butao).
palavra(pais, bolivia).
palavra(pais, bosnia_e_herzegovina).
palavra(pais, botsuana).
palavra(pais, brasil).
palavra(pais, brunei).
palavra(pais, bulgaria).
palavra(pais, burkina_faso).
palavra(pais, burundi).
palavra(pais, cabo_verde).
palavra(pais, camboja).
palavra(pais, camaroes).
palavra(pais, canada).
palavra(pais, catar).
palavra(pais, cazaquistao).
palavra(pais, chade).
palavra(pais, chile).
palavra(pais, china).
palavra(pais, chipre).
palavra(pais, colombia).
palavra(pais, comores).
palavra(pais, congo).
palavra(pais, coreia_do_norte).
palavra(pais, coreia_do_sul).
palavra(pais, costa_do_marfim).
palavra(pais, costa_rica).
palavra(pais, croacia).
palavra(pais, cuba).
palavra(pais, dinamarca).
palavra(pais, djibuti).
palavra(pais, dominica).
palavra(pais, egito).
palavra(pais, el_salvador).
palavra(pais, emirados_arabes_unidos).
palavra(pais, equador).
palavra(pais, eritreia).
palavra(pais, eslovaquia).
palavra(pais, eslovenia).
palavra(pais, espanha).
palavra(pais, estados_unidos).
palavra(pais, estonia).
palavra(pais, eswatini).
palavra(pais, etiopia).
palavra(pais, fiji).
palavra(pais, filipinas).
palavra(pais, finlandia).
palavra(pais, franca).
palavra(pais, gabao).
palavra(pais, gambia).
palavra(pais, gana).
palavra(pais, georgia).
palavra(pais, granada).
palavra(pais, grecia).
palavra(pais, guatemala).
palavra(pais, guiana).
palavra(pais, guine).
palavra(pais, guine_bissau).
palavra(pais, guine_equatorial).
palavra(pais, haiti).
palavra(pais, honduras).
palavra(pais, hungria).
palavra(pais, iemen).
palavra(pais, ilhas_marshall).
palavra(pais, india).
palavra(pais, indonesia).
palavra(pais, ira).
palavra(pais, iraque).
palavra(pais, irlanda).
palavra(pais, islandia).
palavra(pais, israel).
palavra(pais, italia).
palavra(pais, jamaica).
palavra(pais, japao).
palavra(pais, jordania).
palavra(pais, kiribati).
palavra(pais, kuwait).
palavra(pais, laos).
palavra(pais, lesoto).
palavra(pais, letonia).
palavra(pais, libano).
palavra(pais, liberia).
palavra(pais, libia).
palavra(pais, liechtenstein).
palavra(pais, lituania).
palavra(pais, luxemburgo).
palavra(pais, macedonia_do_norte).
palavra(pais, madagascar).
palavra(pais, malasia).
palavra(pais, malawi).
palavra(pais, maldivas).
palavra(pais, mali).
palavra(pais, malta).
palavra(pais, marrocos).
palavra(pais, mauricio).
palavra(pais, mauritania).
palavra(pais, mexico).
palavra(pais, micronesia).
palavra(pais, mocambique).
palavra(pais, moldavia).
palavra(pais, monaco).
palavra(pais, mongolia).
palavra(pais, montenegro).
palavra(pais, myanmar).
palavra(pais, namibia).
palavra(pais, nauru).
palavra(pais, nepal).
palavra(pais, nicaragua).
palavra(pais, niger).
palavra(pais, nigeria).
palavra(pais, noruega).
palavra(pais, nova_zelandia).
palavra(pais, oma).
palavra(pais, paises_baixos).
palavra(pais, palau).
palavra(pais, panama).
palavra(pais, papua_nova_guine).
palavra(pais, paquistao).
palavra(pais, paraguai).
palavra(pais, peru).
palavra(pais, polonia).
palavra(pais, portugal).
palavra(pais, quenia).
palavra(pais, quirguistao).
palavra(pais, reino_unido).
palavra(pais, republica_centro_africana).
palavra(pais, republica_democratica_do_congo).
palavra(pais, republica_dominicana).
palavra(pais, republica_tcheca).
palavra(pais, romenia).
palavra(pais, ruanda).
palavra(pais, russia).
palavra(pais, samoa).
palavra(pais, sao_cristovao_e_neves).
palavra(pais, sao_marinho).
palavra(pais, sao_tome_e_principe).
palavra(pais, sao_vicente_e_granadinas).
palavra(pais, seicheles).
palavra(pais, senegal).
palavra(pais, serra_leoa).
palavra(pais, servia).
palavra(pais, singapura).
palavra(pais, siria).
palavra(pais, somalia).
palavra(pais, sri_lanka).
palavra(pais, sudao).
palavra(pais, sudao_do_sul).
palavra(pais, suecia).
palavra(pais, suica).
palavra(pais, suriname).
palavra(pais, tailandia).
palavra(pais, tajiquistao).
palavra(pais, tanzania).
palavra(pais, timor_leste).
palavra(pais, togo).
palavra(pais, tonga).
palavra(pais, trinidad_e_tobago).
palavra(pais, tunisia).
palavra(pais, turcomenistao).
palavra(pais, turquia).
palavra(pais, tuvalu).
palavra(pais, ucrania).
palavra(pais, uganda).
palavra(pais, uruguai).
palavra(pais, uzbequistao).
palavra(pais, vanuatu).
palavra(pais, venezuela).
palavra(pais, vietna).
palavra(pais, zambia).
palavra(pais, zimbabue).